### PR TITLE
feat: add custom components boilerplate generator

### PR DESCRIPTION
**Pull request by aslauris**

### CODE REVIEW

**Comment by timohubois** [comment]
@aslauris many thanks for the PR. We will bring this up in our next team meeting and come back with a feedback asap.

**Comment by timohubois** [comment]
@aslauris we discussed your PR within the core team. First: We really like the idea of having a solution to create a template structure for new components, and in the past there was a dedicated project called [Flynt Yeoman Generator](https://github.com/flyntwp/generator-flynt), which is currently not heavily maintained, but follows the same idea.

At the moment we think that this kind of functionality should not be part of the core of Flynt itself. Some reasons are that this feature needs to be explained in detail and maintained, and we think it is a better approach to create a new repository and/or package for this feature, where this can be done.

How do you feel about to doing this and when everything is ready we add a link to the [README.md](https://github.com/flyntwp/flynt/blob/master/README.md) from Flynt to get attention to it?

**Comment by timohubois** [comment]
Closed due inactivity.

**Comment by aslauris** [comment]
Hi @timohubois it took me a while to find some time for this. I've just released a CLI tool for scaffolding Flynt2 components: [flynt2-component-scaffolder](https://github.com/aslauris/flynt2-component-scaffolder). I hope Flynt community will find this useful

**Comment by timohubois** [comment]
@aslauris really cool and many thanks for creating it!

I added it with a link here: https://github.com/awesome-flynt/flynt-add-ons

**Pull request closed without merging**
